name: "Combo of Steps"
description: "This action combines multiple steps into a single action"
inputs:
  uri:
    description: 'uri of the endpoint to send the request to'
    required: true
    default: '/api/identity/authentication/v2/test'
outputs:
  my-output:
    description: 'The output of the combo breaker'
    value: ${{ steps.test-outputs.outputs.my-output }}

runs:
  using: "composite"
  steps:
    - name: Run a one-line script
      shell: bash
      run: echo Hello, world!
    # - name: Run a multi-line script
    #   shell: bash
    #   run: |
    #     echo Add other actions to build,
    #     echo test, and deploy your project.
    #     echo "${{ github.event.inputs.uri }}"
    #     echo "${{ inputs.uri }}"
    - name: Test outputs
      id: test-outputs
      shell: bash
      run: |
        echo "my-output=1234" >> $GITHUB_OUTPUT
    # - name: Login to Azure as repository service principal
    #   uses: azure/login@v1
    #   with:
    #     client-id: ${{ vars.AZURE_CLIENT_ID }}
    #     tenant-id: ${{ vars.AZURE_TENANT_ID }}
    #     environment: ${{ vars.AZURE_ENVIRONMENT }}
    #     allow-no-subscriptions: true
