name: "Combo of Steps"
description: "This action combines multiple steps into a single action"
inputs:
  uri:
    description: 'uri of the endpoint to send the request to'
    required: true
    default: '/api/identity/authentication/v2/test'
#   some_other_input:
#     description: 'another input'
#     required: true
#     default: 'here we go'

runs:
  using: "composite"
  steps:
    - name: Run a one-line script
      shell: bash
      run: echo Hello, world!
    - name: Run a multi-line script
      shell: bash
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
        echo "${{ github.event.inputs.uri }}"
        echo "${{ inputs.uri }}"
