# This is a basic workflow to help you get started with Actions

name: Testing Jobs

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
        uri:
          description: 'uri of the endpoint to send the request to'
          required: true
          default: '/api/identity/authentication/v2/test'
        some_other_input:
          description: 'another input'
          required: true
          default: 'here we go'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Print Workflow Dispatch Inputs
        run: echo "${{ toJSON(github.event.inputs) }}"
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - name: Combo Breaker
        id: combo-breaker
        uses: ./.github/actions/combo-step
        with:
          uri: ${{ github.event.inputs.uri }}
        #   some_other_input: ${{ github.event.inputs.some_other_input }}
      - name: Print Combo Breaker Outputs
        run: echo "TEST TEST ${{ toJSON(steps.combo-breaker.outputs) }}"
